const initialProducts = [
 {id:1,title:'Қазақы ұлттық оюлы киіз ноутбук қабы',artisan:'Серік Қалиев',city:'Орал қ.',disability:'Көру қабілеті I топ',price:12500,category:'Киіз бұйымдары',audioDesc:'Биіктігі 28 см, ені 38 см сұр түсті киізден жасалған ноутбук қабы. Ортасында көк түсті ою-өрнегі бар.',bgColor:'#1e3a8a',image:'assets/images/product1.jpg'},
 {id:2,title:'Ағаштан ойылған органайзер',artisan:'Анна Васильева',city:'Атырау қ.',disability:'Қозғалыс аппараты шектелген',price:8500,category:'Ағаш бұйымдары',audioDesc:'Табиғи емен ағашынан жасалған асүйлік кесу тақтасы. Табиғи балауызбен өңделген.',bgColor:'#78350f',image:'assets/images/product2.jpg'},
 {id:3,title:'Керамикалық шай кесе жиынтығы',artisan:'Нұрлан Ахметов',city:'Ақтөбе қ.',disability:'Көру қабілеті II топ',price:15000,category:'Керамика',audioDesc:'4 дана сазкесе. Көгілдір глазурьмен қапталған, ұстағанда бедерлі оюлары сезіледі.',bgColor:'#064e3b',image:'assets/images/product3.jpg'}
];
let products=[...initialProducts], speechEnabled=true, highContrast=true, captured=false;
const $=id=>document.getElementById(id);
function speak(text){if(!speechEnabled||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='kk-KZ';utterance.rate=.9;window.speechSynthesis.speak(utterance)}
function renderProducts(){const query=$('searchInput').value.trim().toLocaleLowerCase('kk');const list=$('productList');list.innerHTML='';const filtered=products.filter(p=>(p.title+' '+p.category+' '+p.artisan).toLocaleLowerCase('kk').includes(query));$('emptyState').hidden=filtered.length>0;filtered.forEach(p=>{const card=document.createElement('article');card.className='card product-card';card.innerHTML=`${p.image?`<img class="product-photo" src="${p.image}" alt="${escapeHtml(p.title)}" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="product-banner" style="background:${p.bgColor}" hidden>🎨 ${escapeHtml(p.category)}</div>`:`<div class="product-banner" style="background:${p.bgColor}">🎨 ${escapeHtml(p.category)}</div>`}<h2 class="product-title">${escapeHtml(p.title)}</h2><p class="price">${Number(p.price).toLocaleString('ru-RU')} ₸</p><div class="artisan">♙ ${escapeHtml(p.artisan)} · ${escapeHtml(p.disability||'Қолөнер шебері')}</div><p class="description">🔊 ${escapeHtml(p.audioDesc||'Қолдан жасалған ерекше бұйым.')}</p><button class="secondary-button speak-button">🔊 Дыбыстау</button><button class="primary-button buy-button">🛍️ Сатып алу (Kaspi)</button>`;card.querySelector('.speak-button').addEventListener('click',()=>speak('Толық сипаттамасы: '+p.title+'. '+p.audioDesc));card.querySelector('.buy-button').addEventListener('click',()=>{speak(p.title+' себетке қосылды.');alert('Бұл демонстрациялық нұсқа. Kaspi төлемі әлі қосылмаған.')});list.appendChild(card)})}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showTab(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.panel').forEach(p=>{const active=p.id===tab;p.hidden=!active;p.classList.toggle('active',active)});const names={marketplace:'Маркетплейс каталогы', 'ai-upload':'Шебер ЖИ бұйым жариялау бөлімі','tech-stack':'Техникалық стек'};speak(names[tab])}
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>showTab(b.dataset.tab)));
$('searchInput').addEventListener('input',renderProducts);
$('speechToggle').addEventListener('click',()=>{speechEnabled=!speechEnabled;$('speechIcon').textContent=speechEnabled?'🔊':'🔇';$('speechToggle').setAttribute('aria-pressed',String(speechEnabled));if(speechEnabled)speak('Экрандық оқырман қосылды.');else if('speechSynthesis'in window)window.speechSynthesis.cancel()});
$('contrastToggle').addEventListener('click',()=>{highContrast=!highContrast;document.body.classList.toggle('normal-mode',!highContrast);document.body.classList.toggle('high-contrast',highContrast);$('contrastIcon').textContent=highContrast?'◉':'◐';speak('Контраст режимі '+(highContrast?'қосылды':'өшірілді'))});
$('photoButton').addEventListener('click',()=>{if(captured)return;let picker=$('realPhotoPicker');if(!picker){picker=document.createElement('input');picker.id='realPhotoPicker';picker.type='file';picker.accept='image/*';picker.setAttribute('capture','environment');picker.hidden=true;document.body.appendChild(picker);picker.addEventListener('change',()=>{const file=picker.files&&picker.files[0];if(!file)return;const old=$('cameraBox').querySelector('.captured-photo');if(old)old.remove();const img=document.createElement('img');img.className='captured-photo';img.alt='Түсірілген бұйым фотосы';img.src=URL.createObjectURL(file);$('cameraBox').prepend(img);$('cameraStatus').textContent='Фото таңдалды. Төмендегі демонстрациялық сипаттаманы тексеріп, жариялай аласыз.';});}picker.click();$('photoButton').disabled=true;$('cameraStatus').textContent='⏳ ЖИ бұйымды талдап жатыр...';$('cameraBox').querySelector('.camera-symbol').textContent='⏳';speak('Сурет түсірілуде. Демонстрациялық ЖИ өнімді талдап жатыр.');setTimeout(()=>{captured=true;$('cameraBox').querySelector('.camera-symbol').textContent='✅';$('cameraStatus').textContent='Өнім сипаттамасының демонстрациялық нұсқасы дайын.';$('publishForm').hidden=false;$('photoButton').hidden=true;$('aiDescription').textContent='Суретте: табиғи қоңыр былғарыдан қолмен тігілген дәстүрлі торсық бұйымы. Бедерлі ұлттық өрнегі бар.';speak('Анықталған өнім: қолдан тігілген былғары торсық. Бағасы 18 000 теңге.');},1400)});
$('publishForm').addEventListener('submit',e=>{e.preventDefault();const title=$('newTitle').value.trim();const price=Number($('newPrice').value);if(!title||!Number.isFinite(price)||price<0)return;products.unshift({id:Date.now(),title,artisan:'Сіз (Шебер)',city:'Орал қ.',disability:'Қолөнер шебері',price,category:'Былғары бұйымдары',audioDesc:$('aiDescription').textContent,bgColor:'#7c2d12'});$('searchInput').value='';renderProducts();showTab('marketplace');$('publishForm').hidden=true;$('photoButton').hidden=false;$('photoButton').disabled=false;$('cameraStatus').textContent='Бұйымды жариялауды бастау үшін төмендегі батырманы басыңыз.';$('cameraBox').querySelector('.camera-symbol').textContent='▣';captured=false;speak('Бұйымыңыз каталогқа қосылды.');});
renderProducts();
